### ISSUE TITLE
Invalid SFTP & FTP

### ISSUE THREAD

**Issue by Rabkaleta** [iAmGio/chorus#37] opened 2021-07-18 22:17 UTC
ip/host:
  ex: node-p1.hoststore.xyz
username:
  ex: hostmember.18238bcx12
and the button said invalid, i tried using ipv4 and sftp://node-p1.hoststore.xyz still not work
sorry my bad english

**Comment by Rabkaleta** [comment] 2021-07-18 22:21
![image](https://user-images.githubusercontent.com/84437677/126083828-8f322b91-d2f2-4230-84b2-cc8880d4e947.png)
no errors

**Comment by iAmGio** [comment] 2021-07-18 22:21
Hi, since 1.3.1 the program prints out the cause of the failed authentication to the console. Please attach the error.

**Comment by Rabkaleta** [comment] 2021-07-18 22:22
![image](https://user-images.githubusercontent.com/84437677/126083860-18a1254b-f49b-4716-aad0-7e448cc0251d.png)
no errors :<

**Comment by Rabkaleta** [comment] 2021-07-18 22:25
help bro, if you can, ill love u man :)

**Comment by iAmGio** [comment] 2021-07-18 22:27
In case I wasn't clear, the error gets printed out after the you try to establish a connection which fails. Did you try to log in with the cmd open?

**Comment by Rabkaleta** [comment] 2021-07-18 22:30
com.jcraft.jsch.JSchException: java.net.UnknownHostException: is-*********.xyz
        at com.jcraft.jsch.Util.createSocket(Util.java:349)
        at com.jcraft.jsch.Session.connect(Session.java:215)
        at com.jcraft.jsch.Session.connect(Session.java:183)
        at org.chorusmc.chorus.connection.SFTPRemoteConnection.<init>(SFTPRemoteConnection.kt:25)
        at org.chorusmc.chorus.menubar.file.OpenFromSFTP.createConnection(OpenRemotely.kt:90)
        at org.chorusmc.chorus.menubar.file.OpenFromSFTP.createConnection(OpenRemotely.kt:84)
        at org.chorusmc.chorus.menubar.file.OpenRemotely$onAction$1.invoke(OpenRemotely.kt:39)
        at org.chorusmc.chorus.menubar.file.OpenRemotely$onAction$1.invoke(OpenRemotely.kt:20)
        at org.chorusmc.chorus.views.remoteconnection.RemoteConnectionView$onConfirm$1.handle(RemoteConnectionView.kt:49)
        at org.chorusmc.chorus.views.remoteconnection.RemoteConnectionView$onConfirm$1.handle(RemoteConnectionView.kt:23)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8886)
        at javafx.scene.control.Button.fire(Button.java:203)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
        at com.sun.glass.ui.View.notifyMouse(View.java:942)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.UnknownHostException: is-**********.xyz
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:645)
        at java.base/java.net.Socket.connect(Socket.java:595)
        at java.base/java.net.Socket.<init>(Socket.java:519)
        at java.base/java.net.Socket.<init>(Socket.java:293)
        at com.jcraft.jsch.Util.createSocket(Util.java:343)
        ... 54 more

**Comment by Rabkaleta** [comment] 2021-07-18 22:32
ahhhhh XD kk, i was type ip[space]|[space]username[space]|[space]port ;-;

**Comment by Rabkaleta** [comment] 2021-07-18 22:32
forgot it :<, im sorry :(

**Comment by iAmGio** [comment] 2021-07-18 22:36
Good to see it fixed 👍
I will make this process easier in the future. Closing this issue meanwhile.

**Closed** 2021-07-18 22:36 UTC
